package org.slyrack.telegrambots.session;

import org.slyrack.telegrambots.exceptions.SessionExistsException;
import org.springframework.lang.NonNull;

import java.util.Optional;

public interface SessionManager {
    /**
     * @param sessionId session id generated by SessionIdGenerator
     * @return new Session with passed id
     * @throws SessionExistsException if session with passed id already exists
     */
    @NonNull
    Session newSession(@NonNull final String sessionId);
    Optional<Session> getSession(@NonNull final String sessionId);
    void update(@NonNull final Session session);
    void delete(@NonNull final Session session);

    void addEventListener(@NonNull final EventType eventType, @NonNull final SessionEventListener listener);

    enum EventType {
        SESSION_NEW,
        SESSION_REQUEST,
        SESSION_UPDATE,
        SESSION_DELETE
    }

    interface SessionEventListener {
        void event(@NonNull final EventType eventType, @NonNull final Session session);
    }
}
